### PR TITLE
Fix go back buttons and unify their style

### PR DESCRIPTION
**Pull request by jennaran**

### CODE REVIEW

**Comment by tonimobin** [comment]
If you click 'Qualifier Names' in the side bar, then click any 'Qualifier name' in the list and click the small 'edit' button in the top of the page, you end up in a loop if you click the 'Go back' buttons. For example ../qualifier_name/36/ <-> ../qualifier_name/36/edit keep looping. The same happens, when you try to delete via the small delete button and in the confirmation screen you click the 'Go back' link - you end up in a loop of ../qualifier_name/36/ <-> ../qualifier_name/36/delete/.

Otherwise the new go back buttons seem to work great! The loops only appear in situations where you can already see one go back, but then you follow some other link and once you end up on the other page that also has a go back, the loop forms.

**Comment by jennaran** [comment]
The problem should be fixed now

**Comment by tonimobin** [comment]
'small edit' button related go backs work great now, but the 'small delete' ones seem to have a minor issue still - gave additional info in Slack.

**Comment by tonimobin** [comment]
All the go backs seem to work now, couldn't find any issues.

**Pull request merged**
